FROM node:18-alpine3.16

WORKDIR /app

# install python and C devkit, needed for some frontend dependencies
ENV PYTHONUNBUFFERED=1
RUN apk add --no-cache python3 build-base && ln -sf python3 /usr/bin/python

# pre-copy dependencies and install them
COPY ./package.json ./package.json
RUN npm install --force

COPY ./public ./public
COPY .env .env
COPY ./src ./src

# launch server
CMD ["npm", "start"]