FROM postgres:15.2-alpine3.17

# Installa dos2unix
RUN apk add --no-cache dos2unix

COPY ./init-scripts/init-users.sh /docker-entrypoint-initdb.d/init-users.sh

# Converte tutti gli script di inizializzazione in formato UNIX (LF)
RUN dos2unix /docker-entrypoint-initdb.d/init-users.sh

RUN chmod +x /docker-entrypoint-initdb.d/init-users.sh
