GRANT CONNECT ON DATABASE ms3_b TO user_ms3_b;
GRANT CREATE ON SCHEMA public TO user_ms3_b;

GRANT USAGE ON SCHEMA public TO user_ms3_b;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_ms3_b;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO user_ms3_b;