GRANT CONNECT ON DATABASE ms3_b TO user_ms3_b;

GRANT ALL PRIVILEGES ON SCHEMA public TO sprintfloyd;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sprintfloyd;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO sprintfloyd;

GRANT USAGE ON SCHEMA public TO user_ms3_b;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user_ms3_b;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user_ms3_b;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_ms3_b;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO user_ms3_b;


