GRANT CONNECT ON DATABASE ms3_public TO user_ms3_public;
GRANT CREATE ON SCHEMA public TO user_ms3_public;

GRANT USAGE ON SCHEMA public TO user_ms3_public;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_ms3_public;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO user_ms3_public;

