GRANT CONNECT ON DATABASE ms3_public TO user_ms3_public;

GRANT USAGE ON SCHEMA public TO user_ms3_public;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO user_ms3_public;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO user_ms3_public;


ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO user_ms3_public;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO user_ms3_public;
