GRANT CONNECT ON DATABASE ms3_a TO user_ms3_a;
GRANT CREATE ON SCHEMA public TO user_ms3_a;

GRANT USAGE ON SCHEMA public TO user_ms3_a;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO user_ms3_a;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO user_ms3_a;



