# setting a value for ENV_VARNAME will overwrite the value of a
# corresponding env.var-name property
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.files.property-placeholders

spring:
    datasource:
        # set mysql.schema as env var for security reasons
        url: "jdbc:mysql://${mysql.host:localhost}:3306/${mysql.schema}"
        
        # spring.datasource.username and spring.datasource.password
        # must be set as env vars for security reasons
        
        driver-class-name: com.mysql.cj.jdbc.Driver
server:
    port: 8080
    servlet:
        context-path: /api